Cmc.Web/Models/UserDTO.cs
using System.ComponentModel.DataAnnotations;

namespace Cmc.Web.Models
{
    // Note: doesn't expose events or behavior
    public class UserDto
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsDone { get; private set; }
    }
}

Cmc.Web/Controllers/Api/ToDoItemsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cmc.Core.Interfaces;
using Cmc.Web.Models;
using Cmc.Web.Filters;
using Cmc.Entities.DBEntities;

namespace Cmc.Web.Controllers.Api
{
    [Route("api/[controller]")]
    [ValidateModel]
    public partial class ToDoController : Controller
    {
        private readonly IWriteRepository<User> _todoRepository;

        public ToDoController(IWriteRepository<User> todoRepository)
        {
            _todoRepository = todoRepository;
        }

        // GET: api/ToDoItems
        [HttpGet]
        public IActionResult List()
        {
            //var items = _todoRepository.All
            //                .Select(item => UserDto.FromToDoItem(item));
            //return Ok(items);
            return Ok();
        }

        // GET: api/ToDoItems
        [HttpGet("{id:int}")]
        public IActionResult GetById(int id)
        {
            //var item = UserDto.FromToDoItem(_todoRepository.GetById(id));
            //return Ok(item);
            return Ok();
        }

        // POST: api/ToDoItems
        public async Task<IActionResult> Post([FromBody] UserDto item)
        {
            //var todoItem = new User()
            //{
            //    Title = item.Title,
            //    Description = item.Description
            //};
            //_todoRepository.Add(todoItem);
            //return Ok(UserDto.FromToDoItem(todoItem));
            return Ok();
        }
    }
}

Cmc.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Cmc.Web.Base;
using Cmc.Interactors.Interfaces;
using Cmc.Interactors;

namespace Cmc.Web.Controllers
{
    public partial class HomeController : BaseController
    {
        private readonly IUserInteractor _userInteractor;

        public HomeController(IMapper mapper, IUserInteractor userInteractor) : base(mapper)
        {
            _userInteractor = userInteractor;
        }

        public IActionResult Index()
        {
            var userRequest = new AddUserRequest() { };
            var response = _userInteractor.Add(new AddUserRequest());
            return View(response);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Cmc.Web/Controllers/ToDoController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Cmc.Core.Interfaces;
using Cmc.Entities.DBEntities;

namespace Cmc.Web.Controllers
{
    public class ToDoController : Controller
    {
        private readonly IWriteRepository<User> _todoRepository;

        public ToDoController(IWriteRepository<User> todoRepository)
        {
            _todoRepository = todoRepository;
        }

        public IActionResult Index()
        {
            return View(_todoRepository.All.ToList());
        }

        public IActionResult Populate()
        {
            int recordsAdded = PopulateDatabase();
            return Ok(recordsAdded);
        }

        public int PopulateDatabase()
        {
            if (_todoRepository.All.Count() > 0) return 0;
            _todoRepository.Add(new User()
            {
                FirstName = "Get Sample Working",
                LastName = "Try to get the sample to build."
            });
            _todoRepository.Add(new User()
            {
                FirstName = "Review Solution",
                LastName = "Review the different projects in the solution and how they relate to one another."
            });
            _todoRepository.Add(new User()
            {
                FirstName = "Run and Review Tests",
                LastName = "Make sure all the tests run and review what they are doing."
            });
            return 3;
        }
    }
}

Cmc.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Cmc.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Cmc.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Clean DDD Architecture Sample";
}

<div class="row">
    <div class="col-md-6">
        <h2>To Do Items</h2>
        <ul>
            <li><a asp-area="" asp-controller="ToDo" asp-action="Populate">Load Sample To Do Items</a></li>
            <li><a asp-area="" asp-controller="ToDo" asp-action="Index">List To Do Items</a></li>
        </ul>
    </div>
    <div class="col-md-6">
        <h2>How to</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
</div>

Cmc.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CleanArchitecture.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CleanArchitecture.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - CleanArchitecture.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Cmc.Web/Views/ToDo/Index.cshtml
@{
    ViewData["Title"] = "ToDo List";
}
@model IEnumerable<Cmc.Core.Entities.User>
<h2>To Do Items</h2>
<ul>
@foreach (var item in Model)
{
    <li>@item.Title<br/>@item.Description</li>    
}
</ul>